### ISSUE TITLE
请问缺的libv2ray模块在哪儿找？

### ISSUE THREAD

**Issue by fudingyu** [xiaokangwang/V2RayGO#1]
Error:A problem occurred configuring project ':app'.

> Cannot evaluate module libv2ray : Configuration with name 'default' not found.

在哪儿找这个模块？

**Comment by xiaokangwang** [comment]
https://github.com/xiaokangwang/AndroidLibV2ray 请使用go编译器编译这个模块，然后导入到Android Studio. 

如果您不是想参与开发，只是想试用，请到这里下载编译好的版本和配置文件。
https://static.kkdev.org/android/V2RayGO/8/

目前V2RayGO处于比较早期的开发状态，如果出现问题请谅解。

**Comment by fudingyu** [comment]
有个麻烦事情，我的手机版本比较低，不能安装这个包！

**Comment by xiaokangwang** [comment]
我是支持Android4.4.2以上的系统,暂时不知道如何兼容比较低的版本。。。我安卓开发现学的。。。。。。抱歉。。

**Comment by ghost** [comment]
@xiaokangwang 老板，能提供nightly预编译的apk供下载么？可以利用travis-ci或者其他ci工具自动构建，发布到github release上面吧。方便大家使用。
非常感谢。

**Comment by xiaokangwang** [comment]
由于构建步骤比较复杂无法移动至CI。如果您希望测试V2RayGO, 请加入测试 Plus https://plus.google.com/communities/101108326638153960485?sqinv=ak90UlpkWWpCLXF4WWdMalhqX1ZubUdCSG9mSEtn .

**Comment by xiaokangwang** [comment]
我们建议用户的设备安装谷歌服务框架和Play商店。V2RayGO的部分功能需要获得这些服务的支持。

**Comment by mwftts** [comment]
SAMSUNG NOTE 8 OERO 装上后好像啥都不点，

**Comment by puyang1017** [comment]
貌似不支持x86模拟器运行呢，能把x86架构编译进库里吗？
