### ISSUE TITLE
没有LIBV2RAY?如何进行配置

### ISSUE THREAD

**Issue by lovetcp** [xiaokangwang/V2RayGO#4]

**Comment by xiaokangwang** [comment]
V2RayGO 中不包括libv2ray的二进制发行文件或编译指导。您可以在 https://github.com/V2Ray-Android/Actinium/tree/master/libv2ray 找到编译好的 libv2ray 或这自行编译 https://github.com/xiaokangwang/AndroidLibV2ray

**Comment by lovetcp** [comment]
那个目录下的V2RAY版本好久没有更新了。。

**Comment by lovetcp** [comment]
都不知道是多少版本。。那个库需要说明与V2ray对应的版本号。这样方便别人改进。

**Comment by xiaokangwang** [comment]
可以使用 libv2ray.CheckVersionX()函数查看libv2ray API版本号和V2Ray版本号。
